spring.application.name=ShopCart
logging.pattern.console=${CONSOLE_LOG_PATTERN:-%clr(%d{HH:mm:ss.SSS}){green} %clr(${PID:- }){magenta} %clr(---){faint} %clr(%-5level){blue} %clr([%thread]){red} %clr(%logger{15}){yellow} - %clr(%msg){cyan}%n}




spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:shopcart}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
